from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys

driver = webdriver.Chrome(r"C:\Users\amar\PycharmProjects\test1\drivers\chromedriver.exe")

driver.set_page_load_timeout(10)
driver.get("https://www.google.com/ ")
driver.find_element_by_name("q").send_keys("hitbullseye")
driver.maximize_window()
driver.find_element_by_name("btnK").send_keys(Keys.ENTER)
a1=driver.find_element_by_class_name("LC20lb")
a1.click()
a2=driver.find_element_by_xpath("/html/body/div[3]/div/header/div/div/div/div/div[3]/a[1]")
a2.click()
driver.find_element_by_xpath("/html/body/div[3]/div/div[9]/div[2]/div[1]/div/div[2]/div/div/div/div[3]/form/div[1]/input").send_keys("amar.salunke.fth@gmail.com")
driver.find_element_by_xpath("/html/body/div[3]/div/div[9]/div[2]/div[1]/div/div[2]/div/div/div/div[3]/form/div[2]/input").send_keys("qwerty7#")
a3=driver.find_element_by_xpath("/html/body/div[3]/div/div[9]/div[2]/div[1]/div/div[2]/div/div/div/div[3]/form/div[3]/input")
a3.click()
time.sleep(3)
a4=driver.find_element_by_xpath("/html/body/app/body/div/bull-leftsidebar/aside/section/ul/li[2]/a/i")
a4.click()
driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-articlesmain/app-articles/div/div[4]/div/div/div/div[1]/div[2]/div[1]/div/input").send_keys("Cutting The Painted Cube")
a5=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-articlesmain/app-articles/div/div[4]/div/div/div/div[1]/div[2]/div[1]/div/button/i")
a5.click()
a6=driver.find_element_by_xpath("/html/body/app/body/div/bull-leftsidebar/aside/section/ul/li[3]/a")
a6.click()
a7=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-testzone/app-testzonemenus/div/div/div/div[4]/div[1]/a/div[2]")
a7.click()
time.sleep(3)
a8=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-testzone/app-testzonemenus/div/div/div/div[4]/div[1]/a/h4")
a8.click()
time.sleep(3)
a9=driver.find_element_by_xpath("/html/body/app/body/div/bull-leftsidebar/aside/section/ul/li[4]/a/i")
a9.click()
time.sleep(3)
s1=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-videos/app-videoresources/div/div/div/div[4]/div[2]/a/h4")
s1.click()
time.sleep(3)
s2=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-videos/app-videoresources/div/div/div/div[4]/div[3]/a/h4")
s2.click()
time.sleep(3)
s3=driver.find_element_by_xpath("/html/body/app/body/div/bull-leftsidebar/aside/section/ul/li[5]/a/i")
s3.click()
time.sleep(3)
s4=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-booking/app-booking/div/div/div/div/div[4]/div/a/h4")
s4.click()
time.sleep(3)
s5=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-booking/app-workshopbooking/div/div/div[4]/div[4]/a/h4")
s5.click()
time.sleep(3)
s6=driver.find_element_by_xpath("/html/body/app/body/div/bull-leftsidebar/aside/section/ul/li[6]/a/i")
s6.click()
time.sleep(3)
#s7=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-alerts/app-alertslist/div/div/div/div/div[6]/a")
#s7.click()

d1=driver.find_element_by_xpath("/html/body/app/body/div/bull-leftsidebar/aside/section/ul/li[7]/a")
d1.click()
time.sleep(3)
d2=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-helpfeedback/app-helpfeedback-list/div/div/div/div/div[4]/div[3]/a")
d2.click()
time.sleep(3)
d3=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-helpfeedback/app-studentsupport/div/div/div[4]/form/div[5]/textarea")
d3.send_keys("Automation testing generated text")
time.sleep(3)
d4=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-helpfeedback/app-studentsupport/div/div/div[2]/a")
d4.click()
time.sleep(4)
d5=driver.find_element_by_xpath("/html/body/app/body/div/bull-leftsidebar/aside/section/ul/li[8]/a/i")
d5.click()
time.sleep(3)
d6=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-myprofile/app-myprofile/div/div/div/div[4]/div[1]/a")
d6.click()
time.sleep(3)
d7=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-myprofile/app-profile/div/div[2]/a")
d7.click()
d8=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-myprofile/app-myprofile/div/div/div/div[4]/div[2]/a/h4")
d8.click()
driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-myprofile/app-password/div/div[4]/form/div[1]/input").send_keys("qwerty7#")
driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-myprofile/app-password/div/div[4]/form/div[2]/input").send_keys("qwerty7#")
driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-myprofile/app-password/div/div[4]/form/div[3]/input").send_keys("qwerty7#")
q1=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-myprofile/app-password/div/div[4]/form/div[4]/input")
q1.click()
time.sleep(3)
q2=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-myprofile/app-password/div/div[6]/div/div/div[3]/button")
q2.click()
time.sleep(3)
q3=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-myprofile/app-password/div/div[2]/a/img")
q3.click()
time.sleep(3)
q4=driver.find_element_by_xpath("/html/body/app/body/div/div/div[2]/app-myprofile/app-myprofile/div/div/div/div[4]/div[3]/a/div[1]")
q4.click()
time.sleep(3)
q5=driver.find_element_by_xpath("/html/body/app/body/div/bullhead/header/nav/div/ul/li[4]/a/span")
q5.click()
time.sleep(3)
q6=driver.find_element_by_xpath("/html/body/app/body/div/bullhead/header/nav/div/ul/li[4]/ul/li[2]/div[2]/a")
q6.click()
time.sleep(3)
driver.quit()
print("Test is completed successfully")
